# Generated by Django 6.0.9 on 2026-10-06 18:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('visitor_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('input_type', models.CharField(choices=[('text', 'Texto'), ('url', 'URL')], max_length=8)),
                ('source_domain', models.CharField(blank=True, max_length=255)),
                ('claim_summary', models.CharField(help_text='Resumo com dados pessoais mascarados.', max_length=255)),
                ('status', models.CharField(choices=[('poucos_sinais_de_risco', 'Poucos sinais de risco'), ('requer_atencao', 'Requer atenção'), ('alto_risco', 'Alto risco'), ('analise_inconclusiva', 'Análise inconclusiva')], max_length=32)),
                ('risk_index', models.FloatField(blank=True, null=True)),
                ('abstention_reasons', models.JSONField(blank=True, default=list)),
                ('model_label', models.CharField(max_length=16)),
                ('model_fake_probability', models.FloatField()),
                ('model_confidence', models.FloatField()),
                ('technical', models.JSONField(default=dict)),
                ('model_version', models.CharField(max_length=64)),
                ('model_sha256', models.CharField(max_length=128)),
                ('rules_version', models.CharField(max_length=32)),
                ('calibrator_version', models.CharField(max_length=32)),
                ('schema_version', models.CharField(max_length=16)),
                ('code_version', models.CharField(blank=True, max_length=64)),
                ('duration_ms', models.FloatField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'análise',
                'verbose_name_plural': 'análises',
                'ordering': ['-created_at'],
            },
        ),
    ]
